### PR TITLE
Code adjustments for @vogdb's review

### PR DESCRIPTION
**Pull request by tomaszdurka**

### CODE REVIEW

**Comment by tomaszdurka** [comment]
@vogdb please review 🐼

**Comment by vogdb** [comment]
It's kind of odd that you have not merged it already >_<

**Comment by tomaszdurka** [comment]
!!!

**Comment by vogdb** [comment]
- 'bin/janus-cluster-manager' uses a wrong path here `var RtpbroadcastReplication = require('./Plugin/RtpbroadcastReplication');`
 - Shall we call `Cluster.super_.call(this)` in its constructor?
 - RtpbroadcastReplicationMountpointList. The same as above.
 - `RtpbroadcastReplicationMountpointList.removeMember` but argument is `mountpoint`. Should it be `removeMountpoint`?
 - `RtpbroadcastReplicationPair.updateMountpoints` you have a line `this.mountpoints.addMember(mountpoint);`. I don't see such method in RtpbroadcastReplicationMountpointList.

**Comment by vogdb** [comment]
@tomaszdurka what is the status here ?

**Comment by tomaszdurka** [comment]
In progress today :)

**Comment by tomaszdurka** [comment]
Ok, merging this, will push more code in other pull-request.

**Pull request merged**
