### PR TITLE
Restructure plugins

### PR DESCRIPTION
**Pull request by tomaszdurka**

### CODE REVIEW

**Comment by tomaszdurka** [comment]
@vogdb merging, please review - best commit by commit

**Comment by vogdb** [comment]
- we should use `super_` property if we inherit by `util.inherits`
```js
function A() {}
function B(){
  B.super_.call(this);
}
util.inherits(B, A);
```
- `Cluster.prototype.register` => `Cluster.prototype.registerServer`? Otherwise we have a misleading name with `registerPlugin`.

**Comment by tomaszdurka** [comment]
Will use `super_` in #24.
Thought about the naming too, I will revisit this in near future (and change it).

**Comment by tomaszdurka** [comment]
Actually naming addressed in #24 too.

**Pull request merged**
