### PR TITLE
Streamline filenames

### PR DESCRIPTION
**Pull request by tomaszdurka**

### CODE REVIEW

**Comment by tomaszdurka** [comment]
@vogdb please review

**Comment by vogdb** [comment]
Well, there is a convention in node.js that all files start with lower case >_<. In all other our projects we have followed that convention.

**Comment by tomaszdurka** [comment]
Convention are for masses! 🐼

**Comment by vogdb** [comment]
Yes yes, as the reviews. The great masters don't need them.

**Pull request merged**
