### PR TITLE
Introduce Rtpbroadcast member/server for storing server data

### PR DESCRIPTION
**Pull request by tomaszdurka**

### CODE REVIEW

**Comment by tomaszdurka** [comment]
@vogdb fyi, please review and add comments if anything should be different.

**Comment by vogdb** [comment]
- does underscore has a method `findAll`? See `RtpbroadcastReplication.prototype.getEdges`.
- `rtpbroadcast` property is not mentioned in `Server` class but is used there.
- `.first().shuffle()` why shuffle one element? See `RtpbroadcastReplication.prototype.getEdges`.

**Comment by vogdb** [comment]
`I was to merge things on my own as well, but somehow persuaded it out of myself ;)` the greatest reviewer in the galaxy (c)

**Comment by tomaszdurka** [comment]
> does underscore has a method findAll? See RtpbroadcastReplication.prototype.getEdges.
Indeed. I should use select/filter. Copy-pasted from earlier-mistake-usage.

> rtpbroadcast property is not mentioned in Server class but is used there.
Yes. It is hard to mention something which is externally added. Maybe there should be `plugins` property on the `Server/Member` that it's easier

> .first().shuffle() why shuffle one element? See RtpbroadcastReplication.prototype.getEdges.
So having list of elements, I group them into multiple lists. Then I take first list (array) and shuffle it.

**Comment by tomaszdurka** [comment]
`findAll` will be fixed in #24.

**Pull request merged**
