### PR TITLE
Extend Plugin functionality with http handlers

### PR DESCRIPTION
**Pull request by tomaszdurka**
Depends on #19

### CODE REVIEW

**Comment by tomaszdurka** [comment]
merging, still @vogdb please review 🐼

**Comment by vogdb** [comment]
We have a potential bug in such setup when `HttpServer` depends on `Cluster` to be in a ready state. I mean that having:
```js
function HttpServer(port, cluster) {
  //...
  this.cluster.plugins.forEach(function(plugin) {
    plugin.installHttpHandlers(router);
  });
```
forces us to always create `HttpServer` after we register all plugins to cluster. That is dangerous.

**Comment by tomaszdurka** [comment]
Well, that is true. Although I thought that all plugins should be set early on.
I would need to trigger event on cluster when plugin is registered.

**Comment by tomaszdurka** [comment]
Addressed in #24.

**Pull request merged**
